# Generated by Django 5.0.4 on 2024-04-15 17:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bullets',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Контент'),
        ),
    ]
