# Generated by Django 5.0.4 on 2024-04-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_bullets_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='accept_status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
