# Generated by Django 5.0.4 on 2024-04-16 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_comment_accept_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='postAuthor',
        ),
    ]
