# Generated by Django 5.0.4 on 2024-04-17 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_alter_comment_commentpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentPost',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='board.bullets', verbose_name='Статья'),
            preserve_default=False,
        ),
    ]
